### ISSUE TITLE
Short bars in the response bar chart

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#18]
With 60+ students in class, the bars appeared so short that a two-digit number was wrapped. Length one-bars made the number 1 illegible.  

It seems that the chart is scaled to fit the number of students. Is it possible to rescale it so that the longest bar fits the width of the chart?

Is it possible to display the number outside the bar, when it is too narrow to show it?

**Comment by sebastsg** [comment]
Bars are now scaled by the most answered response, instead of the total count. This means there is always  at least one bar with 100% width. 
If a bar goes below 15% width, it will display the number outside in black text, and will no longer wrap. This is maybe unlikely to happen now with the change above, but at least it's there just in case.
