### ISSUE TITLE
Difficult UI layout in quiz editor

### ISSUE THREAD

**Issue by hgeorgsch** [KQMATH/moodle-mod_jazzquiz#71]
Refer to the following screen shot posted by @pejhab in #70 :
https://user-images.githubusercontent.com/4097425/116373232-6f489100-a80d-11eb-8a45-66150ca56512.png

Depending on the screen size, it may be difficult to see that the drop-down menu at the bottom of the question selection interface belongs to the «Move To» button, and not to the «Add To Quiz» Button.  This should be improved and tested on different screen sizes.

**Comment by hgeorgsch** [comment]
... help text icons might also help ...

**Comment by jorgenfinsveen** [comment]
Should be possible to improve this. Seems only to require some rearrangement of the elements in the ui. Help text icons should be possible to implement as well.

**Comment by jorgenfinsveen** [comment]
The visuals has been updated since the creation of this issue, so it is already much clearer. I added a line break between the dropdown-menu and the "Add to quiz" button to separate them a bit. I also added a help text icon for the "Add to quiz" button. I tried adding one to the dropdown-menu, but it seems to be a component defined in the Moodle source code rather than Jazzquiz, so I dropped it.

Snapshot of the same page after implementation:

<img width="604" alt="Skjermbilde 2023-07-28 kl  12 03 24" src="https://github.com/KQMATH/moodle-mod_jazzquiz/assets/44703456/c5bb5135-beaf-48cf-8df7-5a5b0ba55278">


Tested with different resolutions and browsers for Bothe Moodle 4.1 and 4.3
